export const TRANSACTION_CATEGORY = {
  BILLS: "Bills",
  BOOKS: "Books",
  BRIZZI_BRI: "Brizzi BRI",
  CABLE_TV: "Cable TV",
  CAFE: "Cafe",
  CASH_WITHDRAWAL: "Cash withdrawal",
  CHARITY_DONATIONS: "Charity & Donations",
  CHILDREN: "Children",
  CONCERT: "Concert",
  COST: "Cost",
  CREDIT_CARD: "Credit card",
  DANA: "DANA",
  DEBT: "Debt",
  DRUGS_MEDICINE: "Drugs/Medicine",
  EDUCATION: "Education",
  ELECTRICITY: "Electricity",
  EMERGENCY_FUND: "Emergency fund",
  ENTERTAINMENT: "Entertainment",
  FAMILY: "Family",
  FASHION: "Fashion",
  FLAZZ_BCA: "Flazz BCA",
  FOODS_DRINKS: "Foods & Drinks",
  FUNERAL: "Funeral",
  GADGET_ELECTRONICS: "Gadget & electronics",
  GAMES: "Games",
  GAS: "Gas",
  GASOLINE: "Gasoline",
  GIFTS: "Gifts",
  GO_PAY: "GoPay",
  GROCERIES: "Groceries",
  GYM_FITNESS: "Gym/Fitness",
  HANG_OUT: "Hang out",
  HEALTHCARE: "Healthcare",
  HOBBY: "Hobby",
  HOUSE_APARTMENT: "House/Apartment",
  HOUSEHOLD_ASSISTANT: "Household assistant",
  INSURANCE: "Insurance",
  INTERNET: "Internet",
  Interest: "Interest",
  INVESTMENT: "Investment",
  LANDLINE: "Landline",
  LAUNDRY: "Laundry",
  LINK_AJA: "LinkAja",
  LOANS: "Loans",
  MAINTENANCE_FEE: "Maintenance fee",
  MANDIRI_EMONEY: "Mandiri e-money",
  MEDICAL_FEE: "Medical fee",
  MOBILE_DATA: "Mobile & Data",
  MORTGAGE: "Mortgage",
  MOVIES_MUSICS: "Movies/Musics",
  OTHERS: "Others",
  OUTGOING: "Outgoing",
  OVO: "OVO",
  PARENT: "Parent",
  PARKING_FEE: "Parking fee",
  PENSION: "Pension",
  PERSONAL_CARE: "Personal care",
  PET: "Pet",
  PUBLIC_TRANSPORT: "Public transport",
  RENOVATION: "Renovation",
  RENT: "Rent",
  RESTAURANT: "Restaurant",
  SAVINGS: "Savings",
  SETTLEMENT: "Settlement",
  SHOPEE_PAY: "ShopeePay",
  SHOPPING: "Shopping",
  SOCIAL_EVENTS: "Social events",
  SPORTS: "Sports",
  STREAMING_SERVICES: "Streaming services",
  SUBSCRIPTIONS: "Subscriptions",
  TAKE_OUTS: "Take outs",
  TAP_CASH: "TapCash",
  TAXES: "Taxes",
  TAXI_OJOL: "Taxi/Ojol",
  TOP_UP: "Top up",
  TOP_UP_CARD: "Top up card",
  TRANSPORTATION: "Transportation",
  TRAVEL_FARES: "Travel fares",
  TUITION_FEE: "Tuition Fee",
  VACATION: "Vacation",
  VEHICLE: "Vehicle",
  VEHICLE_MAINTENANCE: "Vehicle maintenance",
  WATER: "Water",
  WEDDING: "Wedding",
} as const