export const FINANCIAL_ACTIVITY_TYPE = {
  TRANSACTION: 'TRANSACTION',
  POCKET_TRANSFER: 'POCKET_TRANSFER',
  ACCOUNT_TRANSFER: 'ACCOUNT_TRANSFER',
} as const

export type FinancialActivityType = (typeof FINANCIAL_ACTIVITY_TYPE)[keyof typeof FINANCIAL_ACTIVITY_TYPE]