export const RELATIONSHIP_ALIASES = {
  SOURCE_ACCOUNT: 'SOURCE_ACCOUNT',
  DESTINATION_ACCOUNT: 'DESTINATION_ACCOUNT',
  SOURCE_POCKET: 'SOURCE_POCKET',
  DESTINATION_POCKET: 'DESTINATION_POCKET',
} as const;